// Mock data for Champion Select page

export interface ChampionBuild {
  name: string;
  winRate: number;
  pickRate: number;
  games: number;
}

export interface ChampionRunes {
  keystone: string;
  primaryTree: string;
  secondaryTree: string;
  primaryRunes: string[];
  secondaryRunes: string[];
  statShards: [string, string, string];
  winRate: number;
  pickRate: number;
}

export interface ChampionSpells {
  spell1: string;
  spell2: string;
  winRate: number;
  pickRate: number;
}

export interface SkillOrder {
  maxOrder: ["Q" | "W" | "E", "Q" | "W" | "E", "Q" | "W" | "E"]; // Order to max skills
  firstThree: ["Q" | "W" | "E", "Q" | "W" | "E", "Q" | "W" | "E"]; // First 3 levels
  winRate: number;
}

export interface ChampionItems {
  starter: number[];
  core: number[];
  situational: number[];
  boots: number;
  winRate: number;
}

export interface ProBuild {
  proName: string;
  team: string;
  region: string;
  items: number[];
  runes: ChampionRunes;
  spells: ChampionSpells;
  skillOrder: SkillOrder;
  kda: string;
  result: "win" | "loss";
  date: string;
}

export interface ChampionMeta {
  id: string;
  name: string;
  icon: string;
  role: "top" | "jungle" | "mid" | "adc" | "support";
  tier: "S+" | "S" | "A" | "B" | "C" | "D";
  winRate: number;
  pickRate: number;
  banRate: number;
  builds: ChampionItems[];
  runes: ChampionRunes[];
  spells: ChampionSpells[];
  skillOrder: SkillOrder;
  proBuilds: ProBuild[];
  counters: string[];
  synergies: string[];
}

export const ROLES = [
  { id: "top", label: "Top", icon: "🛡️" },
  { id: "jungle", label: "Jungle", icon: "🌲" },
  { id: "mid", label: "Mid", icon: "⚡" },
  { id: "adc", label: "ADC", icon: "🎯" },
  { id: "support", label: "Suporte", icon: "💫" },
] as const;

export const TIER_COLORS: Record<string, string> = {
  "S+": "from-yellow-400 to-amber-500",
  "S": "from-orange-400 to-orange-500",
  "A": "from-emerald-400 to-emerald-500",
  "B": "from-blue-400 to-blue-500",
  "C": "from-slate-400 to-slate-500",
  "D": "from-red-400 to-red-500",
};

const defaultSkillOrder: SkillOrder = {
  maxOrder: ["Q", "W", "E"],
  firstThree: ["Q", "W", "E"],
  winRate: 52.0,
};

const defaultProRunes: ChampionRunes = {
  keystone: "Conqueror",
  primaryTree: "Precision",
  secondaryTree: "Resolve",
  primaryRunes: ["Triumph", "Legend: Tenacity", "Last Stand"],
  secondaryRunes: ["Bone Plating", "Unflinching"],
  statShards: ["Attack Speed", "Adaptive Force", "Health"],
  winRate: 52.0,
  pickRate: 75.0,
};

const defaultProSpells: ChampionSpells = {
  spell1: "Flash",
  spell2: "Teleport",
  winRate: 52.0,
  pickRate: 90.0,
};

export const mockChampionsMeta: ChampionMeta[] = [
  // ============ TOP ============
  {
    id: "ksante",
    name: "K'Sante",
    icon: "https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/KSante.png",
    role: "top",
    tier: "S+",
    winRate: 52.4,
    pickRate: 12.8,
    banRate: 24.5,
    skillOrder: { maxOrder: ["Q", "E", "W"], firstThree: ["Q", "W", "E"], winRate: 53.1 },
    builds: [{ starter: [1054, 2003], core: [6653, 3075, 3065], situational: [3742, 3143, 3053], boots: 3047, winRate: 53.2 }],
    runes: [{ keystone: "Grasp of the Undying", primaryTree: "Resolve", secondaryTree: "Precision", primaryRunes: ["Demolish", "Second Wind", "Overgrowth"], secondaryRunes: ["Legend: Tenacity", "Last Stand"], statShards: ["Attack Speed", "Adaptive Force", "Health"], winRate: 53.8, pickRate: 78.2 }],
    spells: [{ spell1: "Flash", spell2: "Teleport", winRate: 52.4, pickRate: 92.1 }],
    proBuilds: [{ proName: "Zeus", team: "T1", region: "LCK", items: [6653, 3075, 3065, 3742, 3047, 3143], runes: { keystone: "Grasp of the Undying", primaryTree: "Resolve", secondaryTree: "Precision", primaryRunes: ["Demolish", "Second Wind", "Overgrowth"], secondaryRunes: ["Legend: Tenacity", "Last Stand"], statShards: ["Attack Speed", "Adaptive Force", "Health"], winRate: 53.8, pickRate: 78.2 }, spells: { spell1: "Flash", spell2: "Teleport", winRate: 52.4, pickRate: 92.1 }, skillOrder: { maxOrder: ["Q", "E", "W"], firstThree: ["Q", "W", "E"], winRate: 53.1 }, kda: "5/2/8", result: "win", date: "2h atrás" }],
    counters: ["Fiora", "Vayne", "Gwen"],
    synergies: ["Jarvan IV", "Orianna", "Jinx"],
  },
  {
    id: "ambessa",
    name: "Ambessa",
    icon: "https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Ambessa.png",
    role: "top",
    tier: "S+",
    winRate: 53.2,
    pickRate: 15.2,
    banRate: 32.1,
    skillOrder: { maxOrder: ["Q", "E", "W"], firstThree: ["Q", "E", "W"], winRate: 53.5 },
    builds: [{ starter: [1055, 2003], core: [6632, 3071, 3053], situational: [3156, 3026, 3742], boots: 3111, winRate: 53.8 }],
    runes: [{ keystone: "Conqueror", primaryTree: "Precision", secondaryTree: "Resolve", primaryRunes: ["Triumph", "Legend: Tenacity", "Last Stand"], secondaryRunes: ["Bone Plating", "Unflinching"], statShards: ["Attack Speed", "Adaptive Force", "Health"], winRate: 53.5, pickRate: 85.3 }],
    spells: [{ spell1: "Flash", spell2: "Ignite", winRate: 53.8, pickRate: 68.4 }],
    proBuilds: [{ proName: "Bin", team: "BLG", region: "LPL", items: [6632, 3071, 3053, 3156, 3111, 3026], runes: defaultProRunes, spells: { spell1: "Flash", spell2: "Ignite", winRate: 53.8, pickRate: 68.4 }, skillOrder: { maxOrder: ["Q", "E", "W"], firstThree: ["Q", "E", "W"], winRate: 53.5 }, kda: "9/3/5", result: "win", date: "4h atrás" }],
    counters: ["Malphite", "Teemo", "Quinn"],
    synergies: ["Lee Sin", "Syndra", "Kai'Sa"],
  },
  {
    id: "jax",
    name: "Jax",
    icon: "https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Jax.png",
    role: "top",
    tier: "S",
    winRate: 51.8,
    pickRate: 10.5,
    banRate: 8.2,
    skillOrder: { maxOrder: ["W", "E", "Q"], firstThree: ["E", "W", "Q"], winRate: 52.1 },
    builds: [{ starter: [1054, 2003], core: [3078, 3053, 3742], situational: [3156, 3026, 3143], boots: 3047, winRate: 52.4 }],
    runes: [{ keystone: "Conqueror", primaryTree: "Precision", secondaryTree: "Resolve", primaryRunes: ["Triumph", "Legend: Tenacity", "Last Stand"], secondaryRunes: ["Bone Plating", "Unflinching"], statShards: ["Attack Speed", "Adaptive Force", "Health"], winRate: 52.2, pickRate: 82.1 }],
    spells: [{ spell1: "Flash", spell2: "Teleport", winRate: 51.8, pickRate: 88.5 }],
    proBuilds: [],
    counters: ["Malphite", "Gragas", "Poppy"],
    synergies: ["Orianna", "Lulu", "Thresh"],
  },
  {
    id: "aatrox",
    name: "Aatrox",
    icon: "https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Aatrox.png",
    role: "top",
    tier: "S",
    winRate: 50.5,
    pickRate: 14.2,
    banRate: 15.8,
    skillOrder: { maxOrder: ["Q", "E", "W"], firstThree: ["Q", "E", "W"], winRate: 50.8 },
    builds: [{ starter: [1054, 2003], core: [6630, 3071, 3053], situational: [3156, 3742, 3026], boots: 3111, winRate: 51.2 }],
    runes: [{ keystone: "Conqueror", primaryTree: "Precision", secondaryTree: "Resolve", primaryRunes: ["Triumph", "Legend: Tenacity", "Last Stand"], secondaryRunes: ["Second Wind", "Revitalize"], statShards: ["Attack Speed", "Adaptive Force", "Health"], winRate: 51.0, pickRate: 88.5 }],
    spells: [{ spell1: "Flash", spell2: "Teleport", winRate: 50.5, pickRate: 85.2 }],
    proBuilds: [],
    counters: ["Fiora", "Irelia", "Riven"],
    synergies: ["Jarvan IV", "Orianna", "Jinx"],
  },
  {
    id: "garen",
    name: "Garen",
    icon: "https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Garen.png",
    role: "top",
    tier: "A",
    winRate: 52.1,
    pickRate: 8.5,
    banRate: 4.2,
    skillOrder: { maxOrder: ["E", "Q", "W"], firstThree: ["Q", "E", "W"], winRate: 52.4 },
    builds: [{ starter: [1054, 2003], core: [3078, 3742, 3065], situational: [3143, 3053, 3075], boots: 3047, winRate: 52.8 }],
    runes: [{ keystone: "Conqueror", primaryTree: "Precision", secondaryTree: "Resolve", primaryRunes: ["Triumph", "Legend: Tenacity", "Last Stand"], secondaryRunes: ["Demolish", "Overgrowth"], statShards: ["Attack Speed", "Adaptive Force", "Health"], winRate: 52.5, pickRate: 75.4 }],
    spells: [{ spell1: "Flash", spell2: "Ignite", winRate: 52.8, pickRate: 72.1 }],
    proBuilds: [],
    counters: ["Vayne", "Quinn", "Teemo"],
    synergies: ["Yuumi", "Lulu", "Thresh"],
  },
  {
    id: "darius",
    name: "Darius",
    icon: "https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Darius.png",
    role: "top",
    tier: "A",
    winRate: 50.8,
    pickRate: 9.2,
    banRate: 18.5,
    skillOrder: { maxOrder: ["Q", "E", "W"], firstThree: ["Q", "W", "E"], winRate: 51.2 },
    builds: [{ starter: [1054, 2003], core: [3078, 3053, 3742], situational: [3143, 3065, 3026], boots: 3047, winRate: 51.5 }],
    runes: [{ keystone: "Conqueror", primaryTree: "Precision", secondaryTree: "Resolve", primaryRunes: ["Triumph", "Legend: Tenacity", "Last Stand"], secondaryRunes: ["Bone Plating", "Unflinching"], statShards: ["Attack Speed", "Adaptive Force", "Health"], winRate: 51.2, pickRate: 82.4 }],
    spells: [{ spell1: "Flash", spell2: "Ghost", winRate: 51.5, pickRate: 78.2 }],
    proBuilds: [],
    counters: ["Vayne", "Quinn", "Kayle"],
    synergies: ["Orianna", "Lulu", "Thresh"],
  },
  {
    id: "mordekaiser",
    name: "Mordekaiser",
    icon: "https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Mordekaiser.png",
    role: "top",
    tier: "B",
    winRate: 49.8,
    pickRate: 6.5,
    banRate: 5.2,
    skillOrder: { maxOrder: ["Q", "E", "W"], firstThree: ["Q", "E", "W"], winRate: 50.1 },
    builds: [{ starter: [1056, 2003], core: [4633, 3116, 3089], situational: [3157, 3065, 3135], boots: 3020, winRate: 50.2 }],
    runes: [{ keystone: "Conqueror", primaryTree: "Precision", secondaryTree: "Resolve", primaryRunes: ["Triumph", "Legend: Tenacity", "Last Stand"], secondaryRunes: ["Second Wind", "Overgrowth"], statShards: ["Attack Speed", "Adaptive Force", "Health"], winRate: 50.0, pickRate: 78.5 }],
    spells: [{ spell1: "Flash", spell2: "Teleport", winRate: 49.8, pickRate: 82.1 }],
    proBuilds: [],
    counters: ["Fiora", "Vayne", "Gwen"],
    synergies: ["Jarvan IV", "Orianna", "Jinx"],
  },

  // ============ JUNGLE ============
  {
    id: "viego",
    name: "Viego",
    icon: "https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Viego.png",
    role: "jungle",
    tier: "S+",
    winRate: 51.9,
    pickRate: 14.5,
    banRate: 18.2,
    skillOrder: { maxOrder: ["Q", "E", "W"], firstThree: ["Q", "W", "E"], winRate: 52.2 },
    builds: [{ starter: [1103, 2003], core: [6672, 6673, 3124], situational: [3156, 3026, 6676], boots: 3006, winRate: 52.8 }],
    runes: [{ keystone: "Conqueror", primaryTree: "Precision", secondaryTree: "Domination", primaryRunes: ["Triumph", "Legend: Alacrity", "Coup de Grace"], secondaryRunes: ["Sudden Impact", "Treasure Hunter"], statShards: ["Attack Speed", "Adaptive Force", "Health"], winRate: 52.2, pickRate: 72.4 }],
    spells: [{ spell1: "Flash", spell2: "Smite", winRate: 51.9, pickRate: 99.8 }],
    proBuilds: [{ proName: "Canyon", team: "GEN.G", region: "LCK", items: [6672, 6673, 3124, 3156, 3006, 3026], runes: { keystone: "Conqueror", primaryTree: "Precision", secondaryTree: "Domination", primaryRunes: ["Triumph", "Legend: Alacrity", "Coup de Grace"], secondaryRunes: ["Sudden Impact", "Treasure Hunter"], statShards: ["Attack Speed", "Adaptive Force", "Health"], winRate: 52.2, pickRate: 72.4 }, spells: { spell1: "Flash", spell2: "Smite", winRate: 51.9, pickRate: 99.8 }, skillOrder: { maxOrder: ["Q", "E", "W"], firstThree: ["Q", "W", "E"], winRate: 52.2 }, kda: "8/1/6", result: "win", date: "5h atrás" }],
    counters: ["Rammus", "Elise", "Nidalee"],
    synergies: ["Orianna", "Lulu", "Jinx"],
  },
  {
    id: "leesin",
    name: "Lee Sin",
    icon: "https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/LeeSin.png",
    role: "jungle",
    tier: "S+",
    winRate: 49.8,
    pickRate: 18.2,
    banRate: 12.4,
    skillOrder: { maxOrder: ["Q", "W", "E"], firstThree: ["Q", "W", "E"], winRate: 50.2 },
    builds: [{ starter: [1103, 2003], core: [6693, 3071, 3156], situational: [3026, 3742, 6676], boots: 3111, winRate: 50.2 }],
    runes: [{ keystone: "Conqueror", primaryTree: "Precision", secondaryTree: "Inspiration", primaryRunes: ["Triumph", "Legend: Tenacity", "Last Stand"], secondaryRunes: ["Magical Footwear", "Cosmic Insight"], statShards: ["Attack Speed", "Adaptive Force", "Health"], winRate: 50.5, pickRate: 65.8 }],
    spells: [{ spell1: "Flash", spell2: "Smite", winRate: 49.8, pickRate: 99.9 }],
    proBuilds: [{ proName: "Peanut", team: "GEN.G", region: "LCK", items: [6693, 3071, 3156, 3026, 3111, 3742], runes: { keystone: "Conqueror", primaryTree: "Precision", secondaryTree: "Inspiration", primaryRunes: ["Triumph", "Legend: Tenacity", "Last Stand"], secondaryRunes: ["Magical Footwear", "Cosmic Insight"], statShards: ["Attack Speed", "Adaptive Force", "Health"], winRate: 50.5, pickRate: 65.8 }, spells: { spell1: "Flash", spell2: "Smite", winRate: 49.8, pickRate: 99.9 }, skillOrder: { maxOrder: ["Q", "W", "E"], firstThree: ["Q", "W", "E"], winRate: 50.2 }, kda: "6/2/12", result: "win", date: "1d atrás" }],
    counters: ["Rammus", "Udyr", "Warwick"],
    synergies: ["Yasuo", "Orianna", "Jinx"],
  },
  {
    id: "reksai",
    name: "Rek'Sai",
    icon: "https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/RekSai.png",
    role: "jungle",
    tier: "S",
    winRate: 52.1,
    pickRate: 8.4,
    banRate: 5.2,
    skillOrder: { maxOrder: ["Q", "E", "W"], firstThree: ["Q", "W", "E"], winRate: 52.4 },
    builds: [{ starter: [1103, 2003], core: [6693, 3071, 3053], situational: [3156, 3742, 3026], boots: 3111, winRate: 52.8 }],
    runes: [{ keystone: "Conqueror", primaryTree: "Precision", secondaryTree: "Domination", primaryRunes: ["Triumph", "Legend: Alacrity", "Coup de Grace"], secondaryRunes: ["Sudden Impact", "Relentless Hunter"], statShards: ["Attack Speed", "Adaptive Force", "Health"], winRate: 52.5, pickRate: 78.2 }],
    spells: [{ spell1: "Flash", spell2: "Smite", winRate: 52.1, pickRate: 99.5 }],
    proBuilds: [],
    counters: ["Elise", "Nidalee", "Kindred"],
    synergies: ["Orianna", "Ahri", "Jinx"],
  },
  {
    id: "jarvan",
    name: "Jarvan IV",
    icon: "https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/JarvanIV.png",
    role: "jungle",
    tier: "S",
    winRate: 51.5,
    pickRate: 9.8,
    banRate: 6.5,
    skillOrder: { maxOrder: ["Q", "E", "W"], firstThree: ["E", "Q", "W"], winRate: 51.8 },
    builds: [{ starter: [1103, 2003], core: [6693, 3071, 3053], situational: [3742, 3143, 3156], boots: 3111, winRate: 52.1 }],
    runes: [{ keystone: "Conqueror", primaryTree: "Precision", secondaryTree: "Resolve", primaryRunes: ["Triumph", "Legend: Tenacity", "Last Stand"], secondaryRunes: ["Bone Plating", "Unflinching"], statShards: ["Attack Speed", "Adaptive Force", "Health"], winRate: 51.8, pickRate: 72.4 }],
    spells: [{ spell1: "Flash", spell2: "Smite", winRate: 51.5, pickRate: 99.2 }],
    proBuilds: [],
    counters: ["Elise", "Nidalee", "Graves"],
    synergies: ["Syndra", "Ahri", "Jinx"],
  },
  {
    id: "elise",
    name: "Elise",
    icon: "https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Elise.png",
    role: "jungle",
    tier: "A",
    winRate: 50.2,
    pickRate: 6.8,
    banRate: 4.5,
    skillOrder: { maxOrder: ["Q", "W", "E"], firstThree: ["W", "Q", "E"], winRate: 50.5 },
    builds: [{ starter: [1103, 2003], core: [4636, 3165, 3157], situational: [3089, 3135, 3102], boots: 3020, winRate: 50.8 }],
    runes: [{ keystone: "Electrocute", primaryTree: "Domination", secondaryTree: "Sorcery", primaryRunes: ["Cheap Shot", "Eyeball Collection", "Relentless Hunter"], secondaryRunes: ["Absolute Focus", "Waterwalking"], statShards: ["Adaptive Force", "Adaptive Force", "Health"], winRate: 50.5, pickRate: 82.1 }],
    spells: [{ spell1: "Flash", spell2: "Smite", winRate: 50.2, pickRate: 99.8 }],
    proBuilds: [],
    counters: ["Graves", "Nocturne", "Shyvana"],
    synergies: ["Syndra", "Orianna", "Caitlyn"],
  },
  {
    id: "graves",
    name: "Graves",
    icon: "https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Graves.png",
    role: "jungle",
    tier: "A",
    winRate: 49.5,
    pickRate: 7.2,
    banRate: 3.8,
    skillOrder: { maxOrder: ["Q", "E", "W"], firstThree: ["Q", "E", "W"], winRate: 49.8 },
    builds: [{ starter: [1103, 2003], core: [6676, 3071, 3156], situational: [3026, 3742, 6693], boots: 3047, winRate: 50.2 }],
    runes: [{ keystone: "Fleet Footwork", primaryTree: "Precision", secondaryTree: "Domination", primaryRunes: ["Triumph", "Legend: Alacrity", "Coup de Grace"], secondaryRunes: ["Sudden Impact", "Treasure Hunter"], statShards: ["Attack Speed", "Adaptive Force", "Health"], winRate: 49.8, pickRate: 68.5 }],
    spells: [{ spell1: "Flash", spell2: "Smite", winRate: 49.5, pickRate: 99.5 }],
    proBuilds: [],
    counters: ["Rammus", "Sejuani", "Amumu"],
    synergies: ["Orianna", "Ahri", "Jinx"],
  },
  {
    id: "warwick",
    name: "Warwick",
    icon: "https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Warwick.png",
    role: "jungle",
    tier: "B",
    winRate: 51.2,
    pickRate: 5.5,
    banRate: 2.8,
    skillOrder: { maxOrder: ["Q", "W", "E"], firstThree: ["Q", "W", "E"], winRate: 51.5 },
    builds: [{ starter: [1103, 2003], core: [6631, 3053, 3742], situational: [3065, 3143, 3156], boots: 3047, winRate: 51.8 }],
    runes: [{ keystone: "Press the Attack", primaryTree: "Precision", secondaryTree: "Resolve", primaryRunes: ["Triumph", "Legend: Tenacity", "Last Stand"], secondaryRunes: ["Bone Plating", "Revitalize"], statShards: ["Attack Speed", "Adaptive Force", "Health"], winRate: 51.5, pickRate: 72.4 }],
    spells: [{ spell1: "Flash", spell2: "Smite", winRate: 51.2, pickRate: 99.2 }],
    proBuilds: [],
    counters: ["Kindred", "Lillia", "Karthus"],
    synergies: ["Orianna", "Syndra", "Jinx"],
  },

  // ============ MID ============
  {
    id: "syndra",
    name: "Syndra",
    icon: "https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Syndra.png",
    role: "mid",
    tier: "S+",
    winRate: 51.5,
    pickRate: 9.8,
    banRate: 8.4,
    skillOrder: { maxOrder: ["Q", "W", "E"], firstThree: ["Q", "E", "W"], winRate: 51.8 },
    builds: [{ starter: [1056, 2003], core: [6653, 3165, 3089], situational: [3135, 3157, 4645], boots: 3020, winRate: 52.1 }],
    runes: [{ keystone: "Electrocute", primaryTree: "Domination", secondaryTree: "Sorcery", primaryRunes: ["Cheap Shot", "Eyeball Collection", "Ultimate Hunter"], secondaryRunes: ["Manaflow Band", "Transcendence"], statShards: ["Adaptive Force", "Adaptive Force", "Health"], winRate: 52.4, pickRate: 68.5 }],
    spells: [{ spell1: "Flash", spell2: "Teleport", winRate: 51.8, pickRate: 55.2 }],
    proBuilds: [{ proName: "Faker", team: "T1", region: "LCK", items: [6653, 3165, 3089, 3135, 3020, 3157], runes: { keystone: "Electrocute", primaryTree: "Domination", secondaryTree: "Sorcery", primaryRunes: ["Cheap Shot", "Eyeball Collection", "Ultimate Hunter"], secondaryRunes: ["Manaflow Band", "Transcendence"], statShards: ["Adaptive Force", "Adaptive Force", "Health"], winRate: 52.4, pickRate: 68.5 }, spells: { spell1: "Flash", spell2: "Teleport", winRate: 51.8, pickRate: 55.2 }, skillOrder: { maxOrder: ["Q", "W", "E"], firstThree: ["Q", "E", "W"], winRate: 51.8 }, kda: "8/1/7", result: "win", date: "8h atrás" }],
    counters: ["Fizz", "Zed", "Yasuo"],
    synergies: ["Jarvan IV", "Thresh", "Jinx"],
  },
  {
    id: "ahri",
    name: "Ahri",
    icon: "https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Ahri.png",
    role: "mid",
    tier: "S+",
    winRate: 52.1,
    pickRate: 11.4,
    banRate: 5.2,
    skillOrder: { maxOrder: ["Q", "W", "E"], firstThree: ["Q", "W", "E"], winRate: 52.4 },
    builds: [{ starter: [1056, 2003], core: [4645, 3165, 3089], situational: [3135, 3157, 3102], boots: 3020, winRate: 52.8 }],
    runes: [{ keystone: "Electrocute", primaryTree: "Domination", secondaryTree: "Inspiration", primaryRunes: ["Cheap Shot", "Eyeball Collection", "Ultimate Hunter"], secondaryRunes: ["Biscuit Delivery", "Cosmic Insight"], statShards: ["Adaptive Force", "Adaptive Force", "Health"], winRate: 53.2, pickRate: 82.1 }],
    spells: [{ spell1: "Flash", spell2: "Ignite", winRate: 52.4, pickRate: 78.5 }],
    proBuilds: [{ proName: "Chovy", team: "GEN.G", region: "LCK", items: [4645, 3165, 3089, 3135, 3020, 3157], runes: { keystone: "Electrocute", primaryTree: "Domination", secondaryTree: "Inspiration", primaryRunes: ["Cheap Shot", "Eyeball Collection", "Ultimate Hunter"], secondaryRunes: ["Biscuit Delivery", "Cosmic Insight"], statShards: ["Adaptive Force", "Adaptive Force", "Health"], winRate: 53.2, pickRate: 82.1 }, spells: { spell1: "Flash", spell2: "Ignite", winRate: 52.4, pickRate: 78.5 }, skillOrder: { maxOrder: ["Q", "W", "E"], firstThree: ["Q", "W", "E"], winRate: 52.4 }, kda: "7/2/10", result: "win", date: "1d atrás" }],
    counters: ["Kassadin", "Fizz", "Zed"],
    synergies: ["Lee Sin", "Jinx", "Thresh"],
  },
  {
    id: "orianna",
    name: "Orianna",
    icon: "https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Orianna.png",
    role: "mid",
    tier: "S",
    winRate: 50.8,
    pickRate: 8.5,
    banRate: 3.2,
    skillOrder: { maxOrder: ["Q", "W", "E"], firstThree: ["Q", "W", "E"], winRate: 51.1 },
    builds: [{ starter: [1056, 2003], core: [6653, 3165, 3089], situational: [3135, 3157, 3102], boots: 3020, winRate: 51.4 }],
    runes: [{ keystone: "Summon Aery", primaryTree: "Sorcery", secondaryTree: "Inspiration", primaryRunes: ["Manaflow Band", "Transcendence", "Scorch"], secondaryRunes: ["Biscuit Delivery", "Cosmic Insight"], statShards: ["Adaptive Force", "Adaptive Force", "Health"], winRate: 51.2, pickRate: 75.4 }],
    spells: [{ spell1: "Flash", spell2: "Teleport", winRate: 50.8, pickRate: 82.1 }],
    proBuilds: [],
    counters: ["Fizz", "Zed", "Kassadin"],
    synergies: ["Jarvan IV", "Lee Sin", "Jinx"],
  },
  {
    id: "zed",
    name: "Zed",
    icon: "https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Zed.png",
    role: "mid",
    tier: "S",
    winRate: 50.2,
    pickRate: 12.5,
    banRate: 22.4,
    skillOrder: { maxOrder: ["Q", "E", "W"], firstThree: ["Q", "W", "E"], winRate: 50.5 },
    builds: [{ starter: [1055, 2003], core: [6693, 3071, 3156], situational: [6676, 3026, 3139], boots: 3047, winRate: 50.8 }],
    runes: [{ keystone: "Electrocute", primaryTree: "Domination", secondaryTree: "Sorcery", primaryRunes: ["Taste of Blood", "Eyeball Collection", "Ultimate Hunter"], secondaryRunes: ["Absolute Focus", "Gathering Storm"], statShards: ["Adaptive Force", "Adaptive Force", "Health"], winRate: 50.5, pickRate: 85.2 }],
    spells: [{ spell1: "Flash", spell2: "Ignite", winRate: 50.5, pickRate: 92.1 }],
    proBuilds: [],
    counters: ["Lissandra", "Malphite", "Galio"],
    synergies: ["Orianna", "Jarvan IV", "Thresh"],
  },
  {
    id: "viktor",
    name: "Viktor",
    icon: "https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Viktor.png",
    role: "mid",
    tier: "A",
    winRate: 51.2,
    pickRate: 6.8,
    banRate: 2.5,
    skillOrder: { maxOrder: ["E", "Q", "W"], firstThree: ["E", "Q", "W"], winRate: 51.5 },
    builds: [{ starter: [1056, 2003], core: [6653, 3165, 3089], situational: [3135, 3157, 3102], boots: 3020, winRate: 51.8 }],
    runes: [{ keystone: "Summon Aery", primaryTree: "Sorcery", secondaryTree: "Inspiration", primaryRunes: ["Manaflow Band", "Transcendence", "Scorch"], secondaryRunes: ["Biscuit Delivery", "Cosmic Insight"], statShards: ["Adaptive Force", "Adaptive Force", "Health"], winRate: 51.5, pickRate: 72.4 }],
    spells: [{ spell1: "Flash", spell2: "Teleport", winRate: 51.2, pickRate: 78.5 }],
    proBuilds: [],
    counters: ["Fizz", "Zed", "Kassadin"],
    synergies: ["Jarvan IV", "Lee Sin", "Jinx"],
  },
  {
    id: "lux",
    name: "Lux",
    icon: "https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Lux.png",
    role: "mid",
    tier: "A",
    winRate: 51.8,
    pickRate: 7.2,
    banRate: 8.5,
    skillOrder: { maxOrder: ["E", "Q", "W"], firstThree: ["E", "Q", "W"], winRate: 52.1 },
    builds: [{ starter: [1056, 2003], core: [4645, 3165, 3089], situational: [3135, 3157, 3102], boots: 3020, winRate: 52.4 }],
    runes: [{ keystone: "Arcane Comet", primaryTree: "Sorcery", secondaryTree: "Inspiration", primaryRunes: ["Manaflow Band", "Transcendence", "Scorch"], secondaryRunes: ["Biscuit Delivery", "Cosmic Insight"], statShards: ["Adaptive Force", "Adaptive Force", "Health"], winRate: 52.2, pickRate: 78.5 }],
    spells: [{ spell1: "Flash", spell2: "Barrier", winRate: 52.1, pickRate: 65.2 }],
    proBuilds: [],
    counters: ["Fizz", "Zed", "Yasuo"],
    synergies: ["Jarvan IV", "Lee Sin", "Caitlyn"],
  },
  {
    id: "vex",
    name: "Vex",
    icon: "https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Vex.png",
    role: "mid",
    tier: "B",
    winRate: 50.5,
    pickRate: 4.8,
    banRate: 2.1,
    skillOrder: { maxOrder: ["Q", "W", "E"], firstThree: ["Q", "E", "W"], winRate: 50.8 },
    builds: [{ starter: [1056, 2003], core: [4645, 3165, 3089], situational: [3135, 3157, 3102], boots: 3020, winRate: 51.1 }],
    runes: [{ keystone: "Electrocute", primaryTree: "Domination", secondaryTree: "Sorcery", primaryRunes: ["Taste of Blood", "Eyeball Collection", "Ultimate Hunter"], secondaryRunes: ["Manaflow Band", "Transcendence"], statShards: ["Adaptive Force", "Adaptive Force", "Health"], winRate: 50.8, pickRate: 72.4 }],
    spells: [{ spell1: "Flash", spell2: "Ignite", winRate: 50.8, pickRate: 75.2 }],
    proBuilds: [],
    counters: ["Kassadin", "Fizz", "Zed"],
    synergies: ["Jarvan IV", "Lee Sin", "Jinx"],
  },

  // ============ ADC ============
  {
    id: "jinx",
    name: "Jinx",
    icon: "https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Jinx.png",
    role: "adc",
    tier: "S+",
    winRate: 52.8,
    pickRate: 16.5,
    banRate: 12.1,
    skillOrder: { maxOrder: ["Q", "W", "E"], firstThree: ["Q", "W", "E"], winRate: 53.1 },
    builds: [{ starter: [1055, 2003], core: [3031, 3094, 3085], situational: [3036, 3072, 6676], boots: 3006, winRate: 53.4 }],
    runes: [{ keystone: "Lethal Tempo", primaryTree: "Precision", secondaryTree: "Sorcery", primaryRunes: ["Presence of Mind", "Legend: Alacrity", "Coup de Grace"], secondaryRunes: ["Absolute Focus", "Gathering Storm"], statShards: ["Attack Speed", "Adaptive Force", "Health"], winRate: 53.1, pickRate: 88.2 }],
    spells: [{ spell1: "Flash", spell2: "Heal", winRate: 52.8, pickRate: 95.4 }],
    proBuilds: [{ proName: "Gumayusi", team: "T1", region: "LCK", items: [3031, 3094, 3085, 3036, 3006, 3072], runes: { keystone: "Lethal Tempo", primaryTree: "Precision", secondaryTree: "Sorcery", primaryRunes: ["Presence of Mind", "Legend: Alacrity", "Coup de Grace"], secondaryRunes: ["Absolute Focus", "Gathering Storm"], statShards: ["Attack Speed", "Adaptive Force", "Health"], winRate: 53.1, pickRate: 88.2 }, spells: { spell1: "Flash", spell2: "Heal", winRate: 52.8, pickRate: 95.4 }, skillOrder: { maxOrder: ["Q", "W", "E"], firstThree: ["Q", "W", "E"], winRate: 53.1 }, kda: "12/1/9", result: "win", date: "3h atrás" }],
    counters: ["Draven", "Lucian", "Caitlyn"],
    synergies: ["Thresh", "Lulu", "Nautilus"],
  },
  {
    id: "kaisa",
    name: "Kai'Sa",
    icon: "https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Kaisa.png",
    role: "adc",
    tier: "S+",
    winRate: 51.2,
    pickRate: 14.8,
    banRate: 8.5,
    skillOrder: { maxOrder: ["Q", "E", "W"], firstThree: ["Q", "W", "E"], winRate: 51.5 },
    builds: [{ starter: [1055, 2003], core: [6672, 3124, 3115], situational: [3089, 3157, 3135], boots: 3006, winRate: 51.8 }],
    runes: [{ keystone: "Hail of Blades", primaryTree: "Domination", secondaryTree: "Precision", primaryRunes: ["Taste of Blood", "Eyeball Collection", "Treasure Hunter"], secondaryRunes: ["Presence of Mind", "Legend: Alacrity"], statShards: ["Attack Speed", "Adaptive Force", "Health"], winRate: 52.1, pickRate: 75.4 }],
    spells: [{ spell1: "Flash", spell2: "Heal", winRate: 51.2, pickRate: 94.8 }],
    proBuilds: [{ proName: "Ruler", team: "JDG", region: "LPL", items: [6672, 3124, 3115, 3089, 3006, 3157], runes: { keystone: "Hail of Blades", primaryTree: "Domination", secondaryTree: "Precision", primaryRunes: ["Taste of Blood", "Eyeball Collection", "Treasure Hunter"], secondaryRunes: ["Presence of Mind", "Legend: Alacrity"], statShards: ["Attack Speed", "Adaptive Force", "Health"], winRate: 52.1, pickRate: 75.4 }, spells: { spell1: "Flash", spell2: "Heal", winRate: 51.2, pickRate: 94.8 }, skillOrder: { maxOrder: ["Q", "E", "W"], firstThree: ["Q", "W", "E"], winRate: 51.5 }, kda: "10/2/8", result: "win", date: "6h atrás" }],
    counters: ["Miss Fortune", "Draven", "Ashe"],
    synergies: ["Nautilus", "Thresh", "Leona"],
  },
  {
    id: "caitlyn",
    name: "Caitlyn",
    icon: "https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Caitlyn.png",
    role: "adc",
    tier: "S",
    winRate: 51.5,
    pickRate: 12.2,
    banRate: 6.8,
    skillOrder: { maxOrder: ["Q", "W", "E"], firstThree: ["Q", "W", "E"], winRate: 51.8 },
    builds: [{ starter: [1055, 2003], core: [3031, 3094, 3085], situational: [3036, 3072, 6676], boots: 3006, winRate: 52.1 }],
    runes: [{ keystone: "Fleet Footwork", primaryTree: "Precision", secondaryTree: "Sorcery", primaryRunes: ["Presence of Mind", "Legend: Alacrity", "Coup de Grace"], secondaryRunes: ["Absolute Focus", "Gathering Storm"], statShards: ["Attack Speed", "Adaptive Force", "Health"], winRate: 51.8, pickRate: 72.4 }],
    spells: [{ spell1: "Flash", spell2: "Heal", winRate: 51.5, pickRate: 94.2 }],
    proBuilds: [],
    counters: ["Draven", "Lucian", "Samira"],
    synergies: ["Thresh", "Lux", "Morgana"],
  },
  {
    id: "jhin",
    name: "Jhin",
    icon: "https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Jhin.png",
    role: "adc",
    tier: "S",
    winRate: 51.8,
    pickRate: 10.5,
    banRate: 4.2,
    skillOrder: { maxOrder: ["Q", "W", "E"], firstThree: ["Q", "W", "E"], winRate: 52.1 },
    builds: [{ starter: [1055, 2003], core: [3031, 3094, 3085], situational: [3036, 3072, 6676], boots: 3009, winRate: 52.4 }],
    runes: [{ keystone: "Fleet Footwork", primaryTree: "Precision", secondaryTree: "Sorcery", primaryRunes: ["Presence of Mind", "Legend: Alacrity", "Coup de Grace"], secondaryRunes: ["Absolute Focus", "Gathering Storm"], statShards: ["Attack Speed", "Adaptive Force", "Health"], winRate: 52.2, pickRate: 78.5 }],
    spells: [{ spell1: "Flash", spell2: "Heal", winRate: 51.8, pickRate: 92.1 }],
    proBuilds: [],
    counters: ["Draven", "Lucian", "Samira"],
    synergies: ["Thresh", "Xerath", "Morgana"],
  },
  {
    id: "draven",
    name: "Draven",
    icon: "https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Draven.png",
    role: "adc",
    tier: "A",
    winRate: 50.8,
    pickRate: 6.8,
    banRate: 8.5,
    skillOrder: { maxOrder: ["Q", "W", "E"], firstThree: ["Q", "W", "E"], winRate: 51.1 },
    builds: [{ starter: [1055, 2003], core: [6676, 3031, 3094], situational: [3036, 3072, 3085], boots: 3006, winRate: 51.4 }],
    runes: [{ keystone: "Conqueror", primaryTree: "Precision", secondaryTree: "Domination", primaryRunes: ["Triumph", "Legend: Alacrity", "Coup de Grace"], secondaryRunes: ["Taste of Blood", "Treasure Hunter"], statShards: ["Attack Speed", "Adaptive Force", "Health"], winRate: 51.2, pickRate: 68.5 }],
    spells: [{ spell1: "Flash", spell2: "Heal", winRate: 50.8, pickRate: 88.2 }],
    proBuilds: [],
    counters: ["Caitlyn", "Ashe", "Varus"],
    synergies: ["Thresh", "Leona", "Nautilus"],
  },
  {
    id: "ezreal",
    name: "Ezreal",
    icon: "https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Ezreal.png",
    role: "adc",
    tier: "A",
    winRate: 49.5,
    pickRate: 15.2,
    banRate: 2.1,
    skillOrder: { maxOrder: ["Q", "E", "W"], firstThree: ["Q", "E", "W"], winRate: 49.8 },
    builds: [{ starter: [1083, 2003], core: [6672, 3004, 3042], situational: [3508, 3156, 3026], boots: 3158, winRate: 50.1 }],
    runes: [{ keystone: "Conqueror", primaryTree: "Precision", secondaryTree: "Inspiration", primaryRunes: ["Presence of Mind", "Legend: Alacrity", "Coup de Grace"], secondaryRunes: ["Biscuit Delivery", "Cosmic Insight"], statShards: ["Attack Speed", "Adaptive Force", "Health"], winRate: 49.8, pickRate: 72.4 }],
    spells: [{ spell1: "Flash", spell2: "Heal", winRate: 49.5, pickRate: 85.2 }],
    proBuilds: [],
    counters: ["Draven", "Lucian", "Miss Fortune"],
    synergies: ["Karma", "Yuumi", "Lulu"],
  },
  {
    id: "ashe",
    name: "Ashe",
    icon: "https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Ashe.png",
    role: "adc",
    tier: "B",
    winRate: 50.2,
    pickRate: 5.5,
    banRate: 1.8,
    skillOrder: { maxOrder: ["W", "Q", "E"], firstThree: ["W", "Q", "E"], winRate: 50.5 },
    builds: [{ starter: [1055, 2003], core: [3031, 3085, 3094], situational: [3036, 3072, 6676], boots: 3006, winRate: 50.8 }],
    runes: [{ keystone: "Lethal Tempo", primaryTree: "Precision", secondaryTree: "Sorcery", primaryRunes: ["Presence of Mind", "Legend: Alacrity", "Coup de Grace"], secondaryRunes: ["Absolute Focus", "Gathering Storm"], statShards: ["Attack Speed", "Adaptive Force", "Health"], winRate: 50.5, pickRate: 75.4 }],
    spells: [{ spell1: "Flash", spell2: "Heal", winRate: 50.2, pickRate: 92.1 }],
    proBuilds: [],
    counters: ["Draven", "Lucian", "Samira"],
    synergies: ["Thresh", "Lux", "Morgana"],
  },

  // ============ SUPPORT ============
  {
    id: "lulu",
    name: "Lulu",
    icon: "https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Lulu.png",
    role: "support",
    tier: "S+",
    winRate: 52.4,
    pickRate: 10.2,
    banRate: 15.8,
    skillOrder: { maxOrder: ["E", "W", "Q"], firstThree: ["E", "Q", "W"], winRate: 52.8 },
    builds: [{ starter: [3850, 2003], core: [6617, 3011, 3504], situational: [3107, 3222, 3190], boots: 3158, winRate: 52.8 }],
    runes: [{ keystone: "Summon Aery", primaryTree: "Sorcery", secondaryTree: "Resolve", primaryRunes: ["Manaflow Band", "Transcendence", "Scorch"], secondaryRunes: ["Font of Life", "Revitalize"], statShards: ["Ability Haste", "Adaptive Force", "Health"], winRate: 53.1, pickRate: 85.4 }],
    spells: [{ spell1: "Flash", spell2: "Ignite", winRate: 52.8, pickRate: 68.2 }],
    proBuilds: [{ proName: "Keria", team: "T1", region: "LCK", items: [6617, 3011, 3504, 3107, 3158, 3222], runes: { keystone: "Summon Aery", primaryTree: "Sorcery", secondaryTree: "Resolve", primaryRunes: ["Manaflow Band", "Transcendence", "Scorch"], secondaryRunes: ["Font of Life", "Revitalize"], statShards: ["Ability Haste", "Adaptive Force", "Health"], winRate: 53.1, pickRate: 85.4 }, spells: { spell1: "Flash", spell2: "Exhaust", winRate: 52.5, pickRate: 55.2 }, skillOrder: { maxOrder: ["E", "W", "Q"], firstThree: ["E", "Q", "W"], winRate: 52.8 }, kda: "2/1/18", result: "win", date: "4h atrás" }],
    counters: ["Zyra", "Brand", "Vel'Koz"],
    synergies: ["Jinx", "Kog'Maw", "Twitch"],
  },
  {
    id: "thresh",
    name: "Thresh",
    icon: "https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Thresh.png",
    role: "support",
    tier: "S+",
    winRate: 50.8,
    pickRate: 12.4,
    banRate: 6.2,
    skillOrder: { maxOrder: ["Q", "E", "W"], firstThree: ["E", "Q", "W"], winRate: 51.2 },
    builds: [{ starter: [3858, 2003], core: [3190, 3109, 3107], situational: [3222, 3050, 4401], boots: 3117, winRate: 51.2 }],
    runes: [{ keystone: "Aftershock", primaryTree: "Resolve", secondaryTree: "Inspiration", primaryRunes: ["Font of Life", "Bone Plating", "Unflinching"], secondaryRunes: ["Biscuit Delivery", "Cosmic Insight"], statShards: ["Health", "Armor", "Health"], winRate: 51.5, pickRate: 72.8 }],
    spells: [{ spell1: "Flash", spell2: "Ignite", winRate: 51.2, pickRate: 82.5 }],
    proBuilds: [{ proName: "Keria", team: "T1", region: "LCK", items: [3190, 3109, 3107, 3222, 3117, 3050], runes: { keystone: "Aftershock", primaryTree: "Resolve", secondaryTree: "Inspiration", primaryRunes: ["Font of Life", "Bone Plating", "Unflinching"], secondaryRunes: ["Biscuit Delivery", "Cosmic Insight"], statShards: ["Health", "Armor", "Health"], winRate: 51.5, pickRate: 72.8 }, spells: { spell1: "Flash", spell2: "Ignite", winRate: 51.2, pickRate: 82.5 }, skillOrder: { maxOrder: ["Q", "E", "W"], firstThree: ["E", "Q", "W"], winRate: 51.2 }, kda: "1/2/18", result: "win", date: "6h atrás" }],
    counters: ["Morgana", "Braum", "Alistar"],
    synergies: ["Jinx", "Kai'Sa", "Draven"],
  },
  {
    id: "nautilus",
    name: "Nautilus",
    icon: "https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Nautilus.png",
    role: "support",
    tier: "S",
    winRate: 51.2,
    pickRate: 9.5,
    banRate: 8.5,
    skillOrder: { maxOrder: ["E", "Q", "W"], firstThree: ["Q", "E", "W"], winRate: 51.5 },
    builds: [{ starter: [3858, 2003], core: [3190, 3109, 3107], situational: [3222, 3050, 4401], boots: 3117, winRate: 51.8 }],
    runes: [{ keystone: "Aftershock", primaryTree: "Resolve", secondaryTree: "Inspiration", primaryRunes: ["Font of Life", "Bone Plating", "Unflinching"], secondaryRunes: ["Biscuit Delivery", "Cosmic Insight"], statShards: ["Health", "Armor", "Health"], winRate: 51.8, pickRate: 78.5 }],
    spells: [{ spell1: "Flash", spell2: "Ignite", winRate: 51.5, pickRate: 85.2 }],
    proBuilds: [],
    counters: ["Morgana", "Braum", "Alistar"],
    synergies: ["Jinx", "Kai'Sa", "Draven"],
  },
  {
    id: "leona",
    name: "Leona",
    icon: "https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Leona.png",
    role: "support",
    tier: "S",
    winRate: 51.5,
    pickRate: 8.2,
    banRate: 5.5,
    skillOrder: { maxOrder: ["W", "E", "Q"], firstThree: ["E", "Q", "W"], winRate: 51.8 },
    builds: [{ starter: [3858, 2003], core: [3190, 3109, 3107], situational: [3222, 3050, 4401], boots: 3047, winRate: 52.1 }],
    runes: [{ keystone: "Aftershock", primaryTree: "Resolve", secondaryTree: "Inspiration", primaryRunes: ["Font of Life", "Bone Plating", "Unflinching"], secondaryRunes: ["Biscuit Delivery", "Cosmic Insight"], statShards: ["Health", "Armor", "Health"], winRate: 52.0, pickRate: 82.4 }],
    spells: [{ spell1: "Flash", spell2: "Ignite", winRate: 51.8, pickRate: 78.5 }],
    proBuilds: [],
    counters: ["Morgana", "Braum", "Alistar"],
    synergies: ["Jinx", "Kai'Sa", "Draven"],
  },
  {
    id: "nami",
    name: "Nami",
    icon: "https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Nami.png",
    role: "support",
    tier: "A",
    winRate: 52.1,
    pickRate: 7.5,
    banRate: 3.2,
    skillOrder: { maxOrder: ["W", "E", "Q"], firstThree: ["W", "E", "Q"], winRate: 52.4 },
    builds: [{ starter: [3850, 2003], core: [6617, 3011, 3504], situational: [3107, 3222, 3190], boots: 3158, winRate: 52.8 }],
    runes: [{ keystone: "Summon Aery", primaryTree: "Sorcery", secondaryTree: "Resolve", primaryRunes: ["Manaflow Band", "Transcendence", "Scorch"], secondaryRunes: ["Font of Life", "Revitalize"], statShards: ["Ability Haste", "Adaptive Force", "Health"], winRate: 52.5, pickRate: 78.5 }],
    spells: [{ spell1: "Flash", spell2: "Ignite", winRate: 52.4, pickRate: 72.1 }],
    proBuilds: [],
    counters: ["Blitzcrank", "Leona", "Nautilus"],
    synergies: ["Lucian", "Draven", "Caitlyn"],
  },
  {
    id: "senna",
    name: "Senna",
    icon: "https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Senna.png",
    role: "support",
    tier: "A",
    winRate: 50.5,
    pickRate: 8.8,
    banRate: 4.5,
    skillOrder: { maxOrder: ["Q", "W", "E"], firstThree: ["Q", "W", "E"], winRate: 50.8 },
    builds: [{ starter: [3862, 2003], core: [6632, 3094, 3036], situational: [3072, 3156, 3026], boots: 3009, winRate: 51.2 }],
    runes: [{ keystone: "Fleet Footwork", primaryTree: "Precision", secondaryTree: "Resolve", primaryRunes: ["Presence of Mind", "Legend: Alacrity", "Coup de Grace"], secondaryRunes: ["Bone Plating", "Overgrowth"], statShards: ["Attack Speed", "Adaptive Force", "Health"], winRate: 50.8, pickRate: 68.5 }],
    spells: [{ spell1: "Flash", spell2: "Heal", winRate: 50.5, pickRate: 65.2 }],
    proBuilds: [],
    counters: ["Blitzcrank", "Leona", "Nautilus"],
    synergies: ["Tahm Kench", "Seraphine", "Milio"],
  },
  {
    id: "blitzcrank",
    name: "Blitzcrank",
    icon: "https://ddragon.leagueoflegends.com/cdn/14.24.1/img/champion/Blitzcrank.png",
    role: "support",
    tier: "B",
    winRate: 50.2,
    pickRate: 6.2,
    banRate: 18.5,
    skillOrder: { maxOrder: ["Q", "E", "W"], firstThree: ["Q", "E", "W"], winRate: 50.5 },
    builds: [{ starter: [3858, 2003], core: [3190, 3109, 3107], situational: [3222, 3050, 4401], boots: 3117, winRate: 50.8 }],
    runes: [{ keystone: "Aftershock", primaryTree: "Resolve", secondaryTree: "Inspiration", primaryRunes: ["Font of Life", "Bone Plating", "Unflinching"], secondaryRunes: ["Biscuit Delivery", "Cosmic Insight"], statShards: ["Health", "Armor", "Health"], winRate: 50.5, pickRate: 75.4 }],
    spells: [{ spell1: "Flash", spell2: "Ignite", winRate: 50.5, pickRate: 82.1 }],
    proBuilds: [],
    counters: ["Morgana", "Sivir", "Ezreal"],
    synergies: ["Draven", "Samira", "Lucian"],
  },
];

// Get champions by role
export function getChampionsByRole(role: string): ChampionMeta[] {
  return mockChampionsMeta.filter((c) => c.role === role);
}

// Get top tier champions (S+ and S)
export function getTopTierChampions(): ChampionMeta[] {
  return mockChampionsMeta.filter((c) => c.tier === "S+" || c.tier === "S");
}
